# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Fabric Properties
	minecraft_version=26.1
	loader_version=0.18.4

# Mod Properties
	mod_version = 1.15.0+mc.26.1
	maven_group = com.github.apace100
	archives_base_name = Calio-26.1

# Dependencies
	fabric_version=0.145.3+26.1.1
